name: mbark_iptv
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.0
  responsive_sizer: ^3.2.0
  awesome_snackbar_content: ^0.1.3
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  filling_slider: ^0.0.3
  loading_animation_widget: ^1.2.0+4
  wakelock: ^0.6.2


  #Logic
  azul_envato_checker: ^0.0.3+3
  flutter_bloc: ^8.1.3
  get: ^4.6.6
  intl: ^0.18.1
  get_storage: ^2.1.1
  url_launcher: ^6.2.1
 # wakelock: ^0.6.2
  perfect_volume_control: ^1.0.5
  screen_brightness: ^0.2.2+1

  #M3U
  flutter_vlc_player: ^7.4.0
  pod_player: ^0.2.1



  #Http
  dio: ^5.3.3
  google_mobile_ads: ^3.1.0


dependency_overrides:
  win32: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

